import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import SessionAuthProvider from "@/context/SessionAuthProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SessionAuthProvider>
          <Navbar/>
          {children}
          <Footer/>
        </SessionAuthProvider>
      </body>
    </html>
  );
}
